export const UPDATE_PLAYERS_LIST = 'UPDATE_PLAYERS_LIST';
export const UPDATE_ROOMS_LIST = 'UPDATE_ROOMS_LIST';

export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const SET_ROOM_NAME = 'SET_ROOM_NAME';